import Image from 'next/image';import Link from 'next/link';
export const metadata={title:'Европейский берег'};
export default function Project(){return <article className="projectPage">
<section className="projectHero"><Image src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2200&q=90" alt="Временный placeholder проекта" fill priority/><div className="projectHeroOverlay"/><div className="projectHeroText"><span>Реализованный проект / 01</span><h1>Европейский берег</h1><div>Квартира · 145 м² · 2026</div></div></section>
<section className="projectStory sectionLight"><div><span className="eyebrow">Задача</span><h2>Продумать пространство для современной жизни</h2></div><p>Текст задачи, концепции и исходных ограничений необходимо заменить на реальные данные проекта. Структура уже готова для подробного кейса.</p></section>
<section className="gallery"><Image src="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=88" alt="Интерьер" width={1600} height={950}/><div className="galleryPair"><Image src="https://images.unsplash.com/photo-1600566753051-f0b89df2dd90?auto=format&fit=crop&w=1200&q=86" alt="Деталь интерьера" width={900} height={900}/><Image src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=86" alt="Деталь интерьера" width={900} height={900}/></div><Image src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1800&q=88" alt="Интерьер" width={1600} height={950}/></section>
<section className="projectStory sectionLight"><div><span className="eyebrow">Результат</span><h2>От проекта до готового интерьера</h2></div><p>Добавить фактические материалы, решения, сроки и особенности реализации. При наличии — вставить настоящий slider «визуализация / готовый интерьер».</p></section>
<section className="nextProject"><span>Следующий проект</span><h2>Проект 02</h2><Link href="/projects">Все проекты →</Link></section>
</article>}
